name: CI

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{matrix.os}}
    steps:
      - name: Checkout zig-minirv32
        uses: actions/checkout@v2
        with:
          path: zig-minirv32
      - name: Setup Zig
        uses: mlugg/setup-zig@v1
        with:
          version: 0.13.0
      - name: Build emu
        run: zig build
        working-directory: zig-minirv32
      - name: Build hello
        run: zig build
        working-directory: zig-minirv32/samples/hello
      - name: Build mandelbrot
        run: zig build
        working-directory: zig-minirv32/samples/mandelbrot
      - name: Build shell
        run: zig build
        working-directory: zig-minirv32/samples/shell

